### ISSUE TITLE
Context put fails if applied in Business Knowledge Model

### ISSUE THREAD

**Issue by kunalgithub** [tarilabs/dmn-data-enrichment-20210804#1]
``` syntax error near 'put' (resource: ```

`input as Array of Object `
Decision -- for I in ArrayOfObjects return calculate(I)
```
 Business Knowledge Model -- context put ( I , "x","aa") 
```

![image](https://user-images.githubusercontent.com/7925742/192165460-726745e3-fab7-4392-a47d-5b666a7f607e.png)

**Comment by tarilabs** [comment]
`context put` is from DMNv1.4, you are likely using an old version. 

Update to a newer version of Drools DMN engine which will include support to DMNv1.4 constructs.

**Comment by tarilabs** [comment]
also, end parens is missing `)` at the end of the expression.
